import os                          # For file and directory operations
import glob                         # For recursively finding all face image files
import cv2                          # OpenCV for reading images from disk
import numpy as np                  # NumPy for numerical operations and DCT computation
from scipy.fftpack import dct       # Scipy's fast 2D Discrete Cosine Transform
from tqdm import tqdm               # Progress bar for long-running loops


def compute_dct_features(image, num_coefficients=64):
    """
    Computes the Discrete Cosine Transform (DCT) of a grayscale image and
    returns the most significant low-frequency coefficients as a feature vector.

    The DCT converts an image from the spatial domain (pixels) to the frequency domain.
    Real faces have smooth, natural frequency distributions.
    Deepfakes generated by GANs or diffusion models often leave characteristic
    "checkerboard" or "ringing" artifacts in the high-frequency components.

    Args:
        image (np.ndarray): Input BGR image read by OpenCV (H x W x 3).
        num_coefficients (int): Number of low-frequency DCT coefficients to keep.
                                A smaller number = faster + focuses on global patterns.
                                A larger number = slower + captures more detail.

    Returns:
        np.ndarray: A 1D feature vector of DCT coefficients, shape (num_coefficients * 3,).
    """

    # Initialize a list to hold the DCT features for each color channel
    channel_features = []

    # Process each color channel (B, G, R) separately
    # Deepfake artifacts can appear differently across color channels,
    # so analyzing all three captures more information
    for channel_idx in range(3):
        # Extract just this single channel from the image (shape: H x W)
        channel = image[:, :, channel_idx].astype(np.float32)

        # Apply the 2D DCT by running 1D DCT row-wise, then column-wise
        # norm='ortho' scales the transform for energy conservation (standard practice)
        dct_2d = dct(dct(channel, axis=0, norm='ortho'), axis=1, norm='ortho')

        # Flatten the 2D DCT matrix into a 1D array
        # The top-left corner of the DCT contains the most important low-frequency info
        dct_flat = dct_2d.flatten()

        # Keep only the first 'num_coefficients' values
        # These low-frequency coefficients capture the global structure of the face
        # High-frequency coefficients (the rest) contain noise and fine details
        dct_truncated = dct_flat[:num_coefficients]

        # Normalize the coefficients to zero mean and unit variance
        # This makes the features scale-invariant and improves model training stability
        mean = np.mean(dct_truncated)                   # Calculate mean of the feature vector
        std  = np.std(dct_truncated) + 1e-8             # Add small epsilon to avoid division by zero
        dct_normalized = (dct_truncated - mean) / std   # Standardize the vector

        # Add the normalized features for this channel to our list
        channel_features.append(dct_normalized)

    # Concatenate the 3 channel feature vectors into one 1D array
    # Resulting shape: (num_coefficients * 3,), e.g., (192,) if num_coefficients=64
    return np.concatenate(channel_features)


def extract_frequency_features(face_dir="faces", freq_dir="frequency_features", num_coefficients=64):
    """
    Iterates over all cropped face images and extracts DCT-based frequency features.
    Saves per-video feature arrays as .npy files for downstream model training.

    Args:
        face_dir (str):          Root directory of cropped face images (from Phase 5).
        freq_dir (str):          Root directory where .npy frequency feature files will be saved.
        num_coefficients (int):  Number of low-frequency DCT coefficients to use per channel.
    """

    # Verify that the face directory from Phase 5 exists
    if not os.path.exists(face_dir):
        print(f"Error: Face directory '{face_dir}' not found. Run extract_faces.py first.")
        return

    # Create the output directory for frequency features
    os.makedirs(freq_dir, exist_ok=True)

    # Recursively find all .jpg face image files under the faces/ directory
    face_paths = glob.glob(os.path.join(face_dir, "**", "*.jpg"), recursive=True)
    print(f"Found {len(face_paths)} face images for frequency feature extraction.")

    # Group face images by their parent video using the relative directory structure
    # This mirrors the exact grouping logic used in Phase 6 for spatial features
    video_to_faces = {}
    for face_path in face_paths:
        # Get the path relative to the face_dir root
        relative_path = os.path.relpath(face_path, face_dir)
        path_parts    = relative_path.split(os.sep)  # Split into individual path components

        # Build a video key from the first 3 path parts: category/subset/video_id
        if len(path_parts) >= 3:
            video_key = os.path.join(*path_parts[:3])
        else:
            video_key = os.path.join(*path_parts[:-1])

        # Append this face image path under its video key
        video_to_faces.setdefault(video_key, []).append(face_path)

    print(f"Processing frequency features for {len(video_to_faces)} unique videos...")

    # Process each video's set of face frames
    for video_key, paths in tqdm(video_to_faces.items(), desc="Extracting frequency features"):
        # Sort paths to ensure frames are always in temporal order
        paths = sorted(paths)

        # Accumulate DCT feature vectors for all frames in this video
        frame_features = []

        for face_path in paths:
            # Read the face image from disk using OpenCV (returns BGR format)
            img = cv2.imread(face_path)
            if img is None:
                # Skip any corrupt or missing images
                continue

            # Resize the image to a fixed 224x224 size before DCT
            # This ensures all feature vectors are the same length regardless of crop size
            img_resized = cv2.resize(img, (224, 224))

            # Compute the DCT features for this single face image
            # Returns shape: (num_coefficients * 3,), e.g., (192,)
            features = compute_dct_features(img_resized, num_coefficients=num_coefficients)

            # Add this frame's features to the video's feature list
            frame_features.append(features)

        # Skip this video if no valid face frames were found
        if not frame_features:
            continue

        # Stack all individual frame feature vectors into a 2D array
        # Resulting shape: (num_frames, num_coefficients * 3), e.g., (30, 192)
        features_array = np.stack(frame_features, axis=0)

        # Construct the output .npy save path, mirroring the input directory structure
        save_path = os.path.join(freq_dir, video_key + ".npy")

        # Create the parent directory if it doesn't exist
        os.makedirs(os.path.dirname(save_path), exist_ok=True)

        # Save the frequency feature array to disk in NumPy binary format
        # Shape: (num_frames, 192), e.g., (30, 192)
        np.save(save_path, features_array)

    print(f"\nFrequency feature extraction complete! Features saved to: {freq_dir}")


def visualize_dct(image_path, save_path=None):
    """
    Utility function to visualize the DCT spectrum of a face image.
    This is useful for debugging and for comparing real vs deepfake frequency patterns.

    Args:
        image_path (str): Path to the face image to visualize.
        save_path (str):  Optional path to save the visualization as an image file.
    """
    # Read the image in color
    img = cv2.imread(image_path)
    if img is None:
        print(f"Error: Could not read image: {image_path}")
        return

    # Convert to grayscale for a single-channel frequency visualization
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY).astype(np.float32)

    # Resize to a fixed size for consistent visualization
    gray = cv2.resize(gray, (224, 224))

    # Apply 2D DCT to the grayscale image
    dct_image = dct(dct(gray, axis=0, norm='ortho'), axis=1, norm='ortho')

    # Apply log scaling to the magnitude for better visual contrast
    # This compresses the large range of DCT values into a visible range
    dct_log = np.log(np.abs(dct_image) + 1)

    # Normalize to [0, 255] for display as an image
    dct_visual = cv2.normalize(dct_log, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

    # Show the image if we're in an interactive environment
    cv2.imshow("DCT Frequency Spectrum", dct_visual)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

    # Save the visualization if a save path was provided
    if save_path:
        cv2.imwrite(save_path, dct_visual)
        print(f"DCT visualization saved to: {save_path}")


if __name__ == "__main__":
    # Run the main frequency feature extraction pipeline
    extract_frequency_features()
